# Generated by Django 5.0.2 on 2024-02-24 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('way', models.CharField(max_length=200)),
                ('departure', models.CharField(max_length=30)),
            ],
            options={
                'unique_together': {('name', 'type', 'way')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_system.train')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_system.user')),
            ],
        ),
    ]
