# Generated by Django 5.0.1 on 2024-02-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='departure',
            field=models.DateField(),
        ),
    ]
